#Check https://github.com/crazy-max/diun/blob/master/doc/configuration.md
watch:
  workers: 10
  schedule: "0 * * * *"

notif:
  mail:
    enable: true
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    ssl: false
    insecure_skip_verify: false
    username: aws-ses-username-string
    password: aws-ses-password-string
    from: docker-image-observer@gpupo.com
    to: foo-bar@@gpupo.com

providers:
  static:
    - name: php
      watch_repo: true
      max_tags: 20
      include_tags:
        - ^7\.\d{1,2}\.\d{1,2}-fpm$
    - name: alpine
      watch_repo: true
      max_tags: 20
      include_tags:
        - ^3\.\d{1,2}$
    - name: jwilder/nginx-proxy
      watch_repo: true
      max_tags: 5
